
# ========= genesis =========
num_envs: 12000     # num_envs must larger than num_mini_batches (default=4)! or mini_batch = 0!! 
drone_num: 1
dt: 0.01
max_vis_FPS: 30 
use_FPV_camera: True
max_dis_num: 5
cam_quat: [-0.455, -0.542, 0.542, 0.455]  # FPV camera, 70.0 degree, show in https://quaternions.online/
cam_pos: [0.02, 0.0, 0.04]
cam_res: [256, 256]                      # width, height
drone_init_pos: [0.0, 0.0, 0.4]          # Initial position of the drone
vis_waypoints: True
viewer_follow_drone: False
show_cam_GUI: False
fixed_init_pos: False
# ======== depth cam params ========
znear: 5.0 
zfar: 0.1

# ======== map =========
load_map: False
use_rc: False
show_viewer: True
render_cam: False
controller: "rate"
min_dis: 0.8
map_width: 3.5
map_length: 3.5

# ======== waypoints= ========
init_x_range: [-0.05, 0.05] 
init_y_range: [-0.05, 0.05] 
init_z_range: [0.6, 0.61] 
target_thr: 0.1 







